name: API CI

on:
  push:
    branches:
      - cicd

jobs:
  api-tests:
    name: Run API Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js for API
        uses: actions/setup-node@v2
        with:
          node-version: 19

      - name: Install API Dependencies
        working-directory: ./api
        run: npm install

      - name: Run API Tests
        working-directory: ./api
        run: npm test
