name: Frontend CI

on:
  push:
    branches:
      - cicd

jobs:
  frontend-tests:
    name: Run Frontend Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js for Frontend
        uses: actions/setup-node@v2
        with:
          node-version: 19

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm install

      - name: Run Frontend Unit Tests
        working-directory: ./frontend
        run: npm run test

      - name: Run Frontend E2E Tests
        working-directory: ./frontend
        run: npm run e2e
